### ISSUE TITLE
OpenBVE on Raspberry PI 3?  

### ISSUE THREAD

**Issue by afarlie** [BVE-Reborn/bve-reborn-archive#6]
I appreciate you are re-writing the engine for modern OpenGL techniques..
I noted this:- 
http://hexus.net/tech/news/graphics/90491-raspberry-pi-2-gets-hardware-accelerated-opengl-support/

It would be nice if feasible to be able to have an OpenBVE derived engine that could run on a Pi3, which is cheaper than many desktop systems.

The thought here is museum/heratige attractions use., rather than use in the railway sector.

**Comment by cwfitzgerald** [comment]
I just want to note here, while this may be objectively possible, I'm not sure how practical it would be. Raspberry Pis are slow. Like _really_ slow. Compared to my mid range enterprise laptop, my RPi 2 is 20x slower on the cpu and 4x slower in memory. Compiling things on the RPi is _reaaallyy_ slow. I will get objective performance comparisons of the parser library on the RPi once cmake builds and I can build this library. With such a strict frame time (16.6ms/frame) requirements, the core engine would have to be extremely efficient and the graphics will probably have to be turned down to next to nothing.

None the less, I will be very aware of the possibility and will keep it in mind going forward.

**Comment by cwfitzgerald** [comment]
Just tested compiling on my Raspberry Pi 2. It took over 18 minutes to compile and I could only run 3 jobs due to memory concerns. Compared to my laptop, it compiled approximately 22x times slower than my laptop. The current implementation of the parser, when parsing a fairly standard file finished 10x slower on the pi. While there may be the possibility of getting it running, getting it running and playable will be extremely difficult.

**Comment by afarlie** [comment]
Fair enough. I figured the performance issues might have killed this idea,
